#ifndef __CREDITS_AND_THANKS_H__
#define __CREDITS_AND_THANKS_H__

// Do not edit this file!

namespace CreditsAndThanks {
    const std::string programCredits = "Programming: Frostbyte\r\nBeta Testing: A Friend\r\nWin32++ Library: David Nash (https://sourceforge.net/projects/win32-framework/)\r\n\r\nAdventure Gamer For Windows By: Brian Otridge.";
    const std::string copyright = "© 2022-2023 FrostByte";
}

#endif // __CREDITS_AND_THANKS_H__